name: Playwright E2E Tests

on:
  deployment_status:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  preview:
    uses: DoctorDerek/DoctorDerekCICD/.github/workflows/playwright.yml@d1d38c91a7187e8f22c8228e7d7845193365024a
    with:
      trusted-oidc: true
      prepare-command: pnpm --filter @mapachess/profile... build
